DROP TABLE IF EXISTS Taito CASCADE;
DROP TABLE IF EXISTS Esine CASCADE;
DROP TABLE IF EXISTS Liitos2 CASCADE;
DROP TABLE IF EXISTS Rooli CASCADE;
DROP TABLE IF EXISTS Liitos1 CASCADE;
DROP TABLE IF EXISTS Hahmo CASCADE;
DROP TABLE IF EXISTS Joukkue CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;